apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: gateway-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: auth-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: user-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: user-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: order-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: payment-service
