apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shared-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: infisical
  target:
    name: shared-secrets
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: /shared-secrets/JWT_SECRET