apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
type: Opaque
stringData:
  JWT_SECRET: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24tdGhpcy1pcy1hLTI1Ni1iaXQtc2VjcmV0LWtleS1mb3ItZGV2LW9ubHktY2hhbmdlLWl0"