apiVersion: v1
kind: Service
metadata:
  name: payment-db
spec:
  type: ClusterIP
  selector:
    app: payment-db
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
type: Opaque
stringData:
  POSTGRES_USER: "payment_service"
  POSTGRES_PASSWORD: "payment_secret_123"
  POSTGRES_DB: "payment_service_db"
  POSTGRES_POSTGRES_PASSWORD: "postgres_superuser_payment_db_dev"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-db
spec:
  serviceName: payment-db
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: postgresql
          image: docker.io/bitnami/postgresql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp-postgresql
              containerPort: 5432
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: POSTGRES_DB
            - name: POSTGRESQL_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: POSTGRES_POSTGRES_PASSWORD
            - name: POSTGRESQL_LISTEN_ADDRESSES
              value: "*"
          volumeMounts:
            - name: payment-db-data
              mountPath: /bitnami/postgresql
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "$POSTGRESQL_USERNAME" -d "$POSTGRESQL_DATABASE" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "$POSTGRESQL_USERNAME" -d "$POSTGRESQL_DATABASE" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: payment-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
