apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payment-mongo-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: infisical
  target:
    name: payment-mongo-secret
  data:
    - secretKey: SPRING_DATA_MONGODB_URI
      remoteRef:
        key: /payment-mongo/SPRING_DATA_MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - port: 8084
      targetPort: 8084

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: payment-service
      containers:
        - name: payment-service
          image: docker.io/zhenya465/payment-service:sha-e095084
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: shared-config
            - secretRef:
                name: shared-secrets
            - secretRef:
                name: payment-mongo-secret
          env:
            - name: SERVER_PORT
              value: "8084"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 25
            periodSeconds: 10
            failureThreshold: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
